"""empty message

Revision ID: 03af2f3eddcc
Revises: f832bbbc98dc
Create Date: 2021-02-02 15:36:21.666932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03af2f3eddcc'
down_revision = 'f832bbbc98dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_name')
    # ### end Alembic commands ###
