"""empty message

Revision ID: 0e623cbc1983
Revises: e57cd0e7bddd
Create Date: 2021-02-05 11:39:22.330010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e623cbc1983'
down_revision = 'e57cd0e7bddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_cart_fkey', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'cart', ['cart'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_cart_fkey', 'customer', 'cart', ['cart'], ['id'])
    # ### end Alembic commands ###
