"""empty message

Revision ID: 270847ab0759
Revises: 603c926c3647
Create Date: 2021-02-03 15:56:28.645892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270847ab0759'
down_revision = '603c926c3647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cart', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('post')
    op.drop_table('cart')
    # ### end Alembic commands ###
