"""empty message

Revision ID: 4c18b781abb0
Revises: 1e41211794ef
Create Date: 2021-02-02 15:16:14.097455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c18b781abb0'
down_revision = '1e41211794ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('Категория', sa.String(length=20), nullable=True))
    op.add_column('product', sa.Column('Коллекция товара', sa.Integer(), nullable=True))
    op.drop_constraint('product_Категория товара_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'submenu', ['Коллекция товара'], ['id'])
    op.drop_column('product', 'Категория товара')
    op.drop_column('product', 'Коллекция')
    op.drop_column('product', 'Кол-во элементов')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('Кол-во элементов', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('Коллекция', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('Категория товара', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_Категория товара_fkey', 'product', 'submenu', ['Категория товара'], ['id'])
    op.drop_column('product', 'Коллекция товара')
    op.drop_column('product', 'Категория')
    # ### end Alembic commands ###
