"""empty message

Revision ID: 5f7611b11690
Revises: d6aa3bf2c51b
Create Date: 2021-02-09 14:27:15.305805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7611b11690'
down_revision = 'd6aa3bf2c51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_order_fkey', 'customer', type_='foreignkey')
    op.drop_column('customer', 'order')
    op.add_column('order', sa.Column('customer', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'customer', ['customer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'customer')
    op.add_column('customer', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('customer_order_fkey', 'customer', 'order', ['order'], ['id'])
    # ### end Alembic commands ###
