"""empty message

Revision ID: 65d9931645a2
Revises: 5f7611b11690
Create Date: 2021-02-09 14:30:28.118850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d9931645a2'
down_revision = '5f7611b11690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cart', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'cart', ['cart'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'cart')
    # ### end Alembic commands ###
