"""empty message

Revision ID: 66c56ba8bf61
Revises: 270847ab0759
Create Date: 2021-02-03 16:28:02.938471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c56ba8bf61'
down_revision = '270847ab0759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart', sa.Integer(), nullable=True),
    sa.Column('p', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('customer', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'customer', ['customer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
