"""empty message

Revision ID: c8884ac79178
Revises: 7060227f89ed
Create Date: 2021-02-08 11:56:59.015292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8884ac79178'
down_revision = '7060227f89ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_product', sa.Column('product', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_product', 'product', ['product'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_cart_product_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'cart_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cart_product', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_cart_product_fkey', 'product', 'cart_product', ['cart_product'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.drop_column('cart_product', 'product')
    # ### end Alembic commands ###
