"""empty message

Revision ID: e57cd0e7bddd
Revises: 1fd52c65d4f7
Create Date: 2021-02-05 11:06:25.175444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57cd0e7bddd'
down_revision = '1fd52c65d4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_products',
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('cart_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['cart_product_id'], ['cart_product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_products')
    # ### end Alembic commands ###
